import React from "react";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";  
import Footer from "./components/Footer";
import "../styles/globals.css";  

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bookshop App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
